<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <!--<div style="margin-top: 10px;">
        <label style="padding: 10px;" for="paymee_payment_type">
            <input id="paymee_wire" value="TRANSFER" type="radio" name="paymee_payment_type" class="radio" autocomplete="off" checked="checked">
        </label>
        Transferência Bancária
    </div>
    <div>
        <label style="padding: 10px;" for="paymee_payment_type">
            <input id="paymee_cash" value="CASH" type="radio" name="paymee_payment_type" class="radio" autocomplete="off">
        </label> 
        Pagamento em dinheiro
    </div>-->
    <img src="https://cdn.paymee.com.br/cdn/botao-checkout-horizontal-paguecom-paymee-branco.png" style="margin-top: 10px;width: 350px;">
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
